-- DeepMap — scalable global administration, moderation, bans and staff notifications
-- Run after map-moderator-roles-user-admin-v1.sql.

begin;

create schema if not exists private;

-- =========================================================
-- 1. GENERIC IN-APP NOTIFICATIONS
-- =========================================================

alter table public.user_notifications
    add column if not exists kind text not null default 'submission_review';

alter table public.user_notifications
    add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table public.user_notifications alter column game_id drop not null;
alter table public.user_notifications alter column submission_type drop not null;
alter table public.user_notifications alter column decision drop not null;

alter table public.user_notifications drop constraint if exists user_notifications_submission_type_check;
alter table public.user_notifications drop constraint if exists user_notifications_decision_check;
alter table public.user_notifications drop constraint if exists user_notifications_kind_check;

alter table public.user_notifications
    add constraint user_notifications_kind_check check (
        (kind = 'submission_review' and submission_type in ('create','correction') and decision in ('approved','rejected'))
        or (kind in ('moderator_granted','moderator_revoked','account_suspended','account_reinstated') and submission_type is null and decision is null)
    );

update public.user_notifications
   set kind = 'submission_review'
 where kind is null;

-- =========================================================
-- 2. ACCOUNT SUSPENSIONS / BANS
-- =========================================================

create table if not exists private.deepmap_bans (
    user_id uuid primary key references auth.users(id) on delete cascade,
    reason text not null,
    expires_at timestamptz,
    banned_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    lifted_at timestamptz,
    lifted_by uuid
);

create table if not exists private.deepmap_ban_audit (
    id bigint generated by default as identity primary key,
    actor_id uuid,
    target_user_id uuid not null,
    action text not null check (action in ('user_banned','user_unbanned')),
    reason text,
    expires_at timestamptz,
    created_at timestamptz not null default now()
);

alter table private.deepmap_bans enable row level security;
alter table private.deepmap_ban_audit enable row level security;
revoke all on table private.deepmap_bans from public, anon, authenticated;
revoke all on table private.deepmap_ban_audit from public, anon, authenticated;

create or replace function private.is_deepmap_banned(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
          from private.deepmap_bans as b
         where b.user_id = p_user_id
           and b.lifted_at is null
           and (b.expires_at is null or b.expires_at > now())
    );
$$;

create or replace function private.is_deepmap_banned()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select private.is_deepmap_banned((select auth.uid()));
$$;

revoke all on function private.is_deepmap_banned(uuid) from public, anon, authenticated;
revoke all on function private.is_deepmap_banned() from public, anon, authenticated;
grant execute on function private.is_deepmap_banned() to authenticated;

create or replace function private.can_moderate_deepmap()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select not private.is_deepmap_banned()
       and (private.is_deepmap_admin() or private.is_deepmap_moderator());
$$;

create or replace function public.get_deepmap_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
    select case
        when private.is_deepmap_banned() then 'banned'
        when private.is_deepmap_admin() then 'admin'
        when private.is_deepmap_moderator() then 'moderator'
        else 'user'
    end;
$$;

revoke all on function public.get_deepmap_role() from public, anon, authenticated;
grant execute on function public.get_deepmap_role() to authenticated;

create or replace function public.get_deepmap_account_status()
returns table (
    is_banned boolean,
    reason text,
    expires_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        (b.user_id is not null) as is_banned,
        b.reason,
        b.expires_at
    from (select (select auth.uid()) as uid) as u
    left join private.deepmap_bans as b
      on b.user_id = u.uid
     and b.lifted_at is null
     and (b.expires_at is null or b.expires_at > now());
$$;

revoke all on function public.get_deepmap_account_status() from public, anon, authenticated;
grant execute on function public.get_deepmap_account_status() to authenticated;

create or replace function public.set_deepmap_user_ban(
    p_user_id uuid,
    p_reason text,
    p_expires_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actor uuid := (select auth.uid());
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;
    if p_user_id is null or not exists (select 1 from public.profiles where id = p_user_id) then
        raise exception 'USER_NOT_FOUND' using errcode = 'P0001';
    end if;
    if exists (select 1 from private.deepmap_admins where user_id = p_user_id) then
        raise exception 'ADMIN_ROLE_PROTECTED' using errcode = 'P0001';
    end if;
    if nullif(btrim(coalesce(p_reason,'')), '') is null then
        raise exception 'BAN_REASON_REQUIRED' using errcode = 'P0001';
    end if;
    if p_expires_at is not null and p_expires_at <= now() then
        raise exception 'INVALID_BAN_EXPIRY' using errcode = 'P0001';
    end if;

    insert into private.deepmap_bans (
        user_id, reason, expires_at, banned_by, created_at, updated_at, lifted_at, lifted_by
    ) values (
        p_user_id, btrim(p_reason), p_expires_at, v_actor, now(), now(), null, null
    )
    on conflict (user_id) do update set
        reason = excluded.reason,
        expires_at = excluded.expires_at,
        banned_by = excluded.banned_by,
        updated_at = now(),
        lifted_at = null,
        lifted_by = null;

    insert into private.deepmap_ban_audit (actor_id, target_user_id, action, reason, expires_at)
    values (v_actor, p_user_id, 'user_banned', btrim(p_reason), p_expires_at);

    insert into public.user_notifications (user_id, kind, metadata)
    values (p_user_id, 'account_suspended', jsonb_build_object('reason', btrim(p_reason), 'expires_at', p_expires_at));
end;
$$;

create or replace function public.clear_deepmap_user_ban(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actor uuid := (select auth.uid());
    v_reason text;
    v_expires timestamptz;
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    select reason, expires_at into v_reason, v_expires
      from private.deepmap_bans
     where user_id = p_user_id
       and lifted_at is null;

    update private.deepmap_bans
       set lifted_at = now(), lifted_by = v_actor, updated_at = now()
     where user_id = p_user_id
       and lifted_at is null;

    if found then
        insert into private.deepmap_ban_audit (actor_id, target_user_id, action, reason, expires_at)
        values (v_actor, p_user_id, 'user_unbanned', v_reason, v_expires);
        insert into public.user_notifications (user_id, kind, metadata)
        values (p_user_id, 'account_reinstated', jsonb_build_object('reason', v_reason));
    end if;
end;
$$;

revoke all on function public.set_deepmap_user_ban(uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function public.clear_deepmap_user_ban(uuid) from public, anon, authenticated;
grant execute on function public.set_deepmap_user_ban(uuid, text, timestamptz) to authenticated;
grant execute on function public.clear_deepmap_user_ban(uuid) to authenticated;

-- =========================================================
-- 3. ADMIN USER DIRECTORY + ROLE NOTIFICATIONS
-- =========================================================

drop function if exists public.get_deepmap_users(text, text, integer, integer);
create function public.get_deepmap_users(
    p_role_filter text default 'all',
    p_search text default null,
    p_limit integer default 20,
    p_offset integer default 0
)
returns table (
    user_id uuid,
    username text,
    display_name text,
    joined_at timestamptz,
    role text,
    contribution_count bigint,
    pending_count bigint,
    approved_count bigint,
    rejected_count bigint,
    is_banned boolean,
    ban_reason text,
    ban_expires_at timestamptz,
    total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;
    if p_role_filter not in ('all','user','moderator') then
        raise exception 'INVALID_ROLE_FILTER' using errcode = 'P0001';
    end if;

    return query
    select
        p.id,
        p.username,
        p.public_display_name,
        p.joined_at,
        case when a.user_id is not null then 'admin' when m.user_id is not null then 'moderator' else 'user' end,
        count(s.id)::bigint,
        count(s.id) filter (where s.status='pending')::bigint,
        count(s.id) filter (where s.status='approved')::bigint,
        count(s.id) filter (where s.status='rejected')::bigint,
        (b.user_id is not null),
        b.reason,
        b.expires_at,
        count(*) over()
    from public.profiles p
    left join private.deepmap_admins a on a.user_id=p.id
    left join private.deepmap_moderators m on m.user_id=p.id
    left join public.marker_submissions s on s.submitted_by=p.id
    left join private.deepmap_bans b
      on b.user_id=p.id
     and b.lifted_at is null
     and (b.expires_at is null or b.expires_at > now())
    where (
        nullif(btrim(coalesce(p_search,'')), '') is null
        or p.username ilike '%' || lower(btrim(p_search)) || '%'
    ) and (
        p_role_filter='all'
        or (p_role_filter='user' and a.user_id is null and m.user_id is null)
        or (p_role_filter='moderator' and a.user_id is null and m.user_id is not null)
    )
    group by p.id,p.username,p.public_display_name,p.joined_at,a.user_id,m.user_id,b.user_id,b.reason,b.expires_at
    order by case when a.user_id is not null then 0 when m.user_id is not null then 1 else 2 end, p.username asc
    limit greatest(1,least(coalesce(p_limit,20),100))
    offset greatest(coalesce(p_offset,0),0);
end;
$$;

revoke all on function public.get_deepmap_users(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.get_deepmap_users(text, text, integer, integer) to authenticated;

create or replace function public.set_deepmap_moderator(
    p_user_id uuid,
    p_enabled boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actor uuid := (select auth.uid());
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;
    if p_user_id is null or not exists (select 1 from public.profiles where id = p_user_id) then
        raise exception 'USER_NOT_FOUND' using errcode = 'P0001';
    end if;
    if exists (select 1 from private.deepmap_admins where user_id = p_user_id) then
        raise exception 'ADMIN_ROLE_PROTECTED' using errcode = 'P0001';
    end if;

    if p_enabled then
        insert into private.deepmap_moderators (user_id, created_by)
        values (p_user_id, v_actor)
        on conflict (user_id) do nothing;

        if found then
            insert into private.deepmap_role_audit (actor_id, target_user_id, action)
            values (v_actor, p_user_id, 'moderator_granted');
            insert into public.user_notifications (user_id, kind, metadata)
            values (p_user_id, 'moderator_granted', jsonb_build_object('actor_id', v_actor));
        end if;
    else
        delete from private.deepmap_moderators where user_id = p_user_id;
        if found then
            insert into private.deepmap_role_audit (actor_id, target_user_id, action)
            values (v_actor, p_user_id, 'moderator_revoked');
            insert into public.user_notifications (user_id, kind, metadata)
            values (p_user_id, 'moderator_revoked', jsonb_build_object('actor_id', v_actor));
        end if;
    end if;
end;
$$;

revoke all on function public.set_deepmap_moderator(uuid, boolean) from public, anon, authenticated;
grant execute on function public.set_deepmap_moderator(uuid, boolean) to authenticated;

-- =========================================================
-- 4. GLOBAL MODERATION ACROSS ALL MAPS
-- =========================================================

create or replace function public.get_marker_submissions_page(
    p_game_id text,
    p_status text default 'pending',
    p_limit integer default 10,
    p_offset integer default 0
)
returns table (
    id bigint,
    game_id text,
    marker_id bigint,
    submission_type text,
    correction_kind text,
    status text,
    submitted_by uuid,
    submitted_username text,
    payload jsonb,
    note text,
    reviewed_by uuid,
    reviewed_username text,
    reviewed_at timestamptz,
    review_note text,
    created_at timestamptz,
    updated_at timestamptz,
    revision_count integer,
    total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not private.can_moderate_deepmap() then
        raise exception 'MODERATOR_REQUIRED' using errcode = 'P0001';
    end if;
    if p_status not in ('pending','approved','rejected') then
        raise exception 'INVALID_STATUS' using errcode = 'P0001';
    end if;

    return query
    select
        s.id,s.game_id,s.marker_id,s.submission_type,s.correction_kind,s.status,s.submitted_by,
        submitter.username,s.payload,s.note,s.reviewed_by,reviewer.username,s.reviewed_at,s.review_note,s.created_at,s.updated_at,
        (select count(*)::integer from private.marker_submission_revisions r where r.submission_id=s.id),
        count(*) over()
    from public.marker_submissions s
    left join public.profiles submitter on submitter.id=s.submitted_by
    left join public.profiles reviewer on reviewer.id=s.reviewed_by
    where (p_game_id is null or p_game_id='' or s.game_id=p_game_id)
      and s.status=p_status
    order by case when p_status='pending' then s.updated_at else coalesce(s.reviewed_at,s.updated_at) end desc, s.id desc
    limit greatest(1,least(coalesce(p_limit,10),100))
    offset greatest(coalesce(p_offset,0),0);
end;
$$;

revoke all on function public.get_marker_submissions_page(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.get_marker_submissions_page(text, text, integer, integer) to authenticated;

-- Block suspended users from contribution writes/reads while keeping staff access.
drop policy if exists "marker_submissions_read_own_or_staff" on public.marker_submissions;
create policy "marker_submissions_read_own_or_staff"
on public.marker_submissions
for select
to authenticated
using (
    (submitted_by = (select auth.uid()) and not private.is_deepmap_banned())
    or private.can_moderate_deepmap()
);

drop policy if exists "marker_submissions_insert_own" on public.marker_submissions;
create policy "marker_submissions_insert_own"
on public.marker_submissions
for insert
to authenticated
with check (
    not private.is_deepmap_banned()
    and submitted_by = (select auth.uid())
    and status = 'pending'
    and reviewed_by is null
    and reviewed_at is null
    and review_note is null
);

drop policy if exists "marker_submissions_update_own_pending" on public.marker_submissions;
create policy "marker_submissions_update_own_pending"
on public.marker_submissions
for update
to authenticated
using (
    not private.is_deepmap_banned()
    and submitted_by = (select auth.uid())
    and status = 'pending'
)
with check (
    not private.is_deepmap_banned()
    and submitted_by = (select auth.uid())
    and status = 'pending'
);

-- Current profile editing also respects the app-level suspension.
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id and not private.is_deepmap_banned())
with check ((select auth.uid()) = id and not private.is_deepmap_banned());

-- =========================================================
-- 5. GLOBAL ADMIN AUDIT LOG
-- =========================================================

drop function if exists public.get_deepmap_admin_audit(integer, integer);
create function public.get_deepmap_admin_audit(
    p_limit integer default 25,
    p_offset integer default 0
)
returns table (
    event_id text,
    action text,
    actor_username text,
    target_username text,
    game_id text,
    submission_id bigint,
    detail text,
    created_at timestamptz,
    total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    return query
    with events as (
        select
            'role-' || r.id::text as event_id,
            r.action,
            actor.username as actor_username,
            target.username as target_username,
            null::text as game_id,
            null::bigint as submission_id,
            null::text as detail,
            r.created_at
        from private.deepmap_role_audit r
        left join public.profiles actor on actor.id=r.actor_id
        left join public.profiles target on target.id=r.target_user_id

        union all

        select
            'ban-' || b.id::text,
            b.action,
            actor.username,
            target.username,
            null::text,
            null::bigint,
            case
                when b.action='user_banned' then coalesce(b.reason,'') || case when b.expires_at is null then ' · permanent' else ' · until ' || b.expires_at::text end
                else coalesce(b.reason,'')
            end,
            b.created_at
        from private.deepmap_ban_audit b
        left join public.profiles actor on actor.id=b.actor_id
        left join public.profiles target on target.id=b.target_user_id

        union all

        select
            'submission-' || s.id::text || '-' || s.status,
            case when s.status='approved' then 'submission_approved' else 'submission_rejected' end,
            reviewer.username,
            submitter.username,
            s.game_id,
            s.id,
            nullif(s.review_note,''),
            coalesce(s.reviewed_at,s.updated_at)
        from public.marker_submissions s
        left join public.profiles reviewer on reviewer.id=s.reviewed_by
        left join public.profiles submitter on submitter.id=s.submitted_by
        where s.status in ('approved','rejected')
    )
    select
        e.event_id,e.action,e.actor_username,e.target_username,e.game_id,e.submission_id,e.detail,e.created_at,
        count(*) over()
    from events e
    order by e.created_at desc
    limit greatest(1,least(coalesce(p_limit,25),100))
    offset greatest(coalesce(p_offset,0),0);
end;
$$;

revoke all on function public.get_deepmap_admin_audit(integer, integer) from public, anon, authenticated;
grant execute on function public.get_deepmap_admin_audit(integer, integer) to authenticated;

commit;
