-- DeepMap v1.0.31 — 03 | Elden Ring Map Data
-- Estrutura base dos marcadores do mapa, armas e respetivos upgrades.

-- 1. Tabela para os Marcadores do Mapa
CREATE TABLE marcadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jogo VARCHAR DEFAULT 'elden-ring',
      titulo VARCHAR NOT NULL,
        categoria VARCHAR NOT NULL, -- Ex: 'boss', 'arma', 'graca', 'item'
          coordenada_x FLOAT NOT NULL,
            coordenada_y FLOAT NOT NULL,
              descricao_pt TEXT,
                descricao_en TEXT,
                  video_url TEXT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
                    );

                    -- 2. Tabela para as Armas
                    CREATE TABLE armas (
                      id VARCHAR PRIMARY KEY, -- Ex: 'greatsword', 'uchigatana'
                        nome VARCHAR NOT NULL,
                          tipo VARCHAR NOT NULL, -- Ex: 'Colossal Sword', 'Katana'
                            descricao_pt TEXT,
                              descricao_en TEXT,
                                requisitos_atributos JSONB, -- Ex: {"forca": 31, "destreza": 12}
                                  imagem_url TEXT
                                  );

                                  -- 3. Tabela para os Upgrades de Armas (+1 a +25)
                                  CREATE TABLE arma_upgrades (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      arma_id VARCHAR REFERENCES armas(id) ON DELETE CASCADE,
                                        nivel INT NOT NULL, -- 0, 1, 2... ate 25
                                          dano_fisico INT NOT NULL,
                                            scaling_forca VARCHAR(2), -- 'D', 'C', 'B', 'A', 'S'
                                              scaling_destreza VARCHAR(2),
                                                materiais VARCHAR NOT NULL -- Ex: '2x Smithing Stone [1]'
                                                );
