-- DeepMap — moderator roles, admin user management and moderator review access
-- Run after the previous Editor 2.0/community moderation migrations.

begin;

create schema if not exists private;

-- =========================================================
-- 1. MODERATOR ROLE + ROLE AUDIT
-- =========================================================

create table if not exists private.deepmap_moderators (
    user_id uuid primary key
        references auth.users(id)
        on delete cascade,
    created_by uuid,
    created_at timestamptz not null default now()
);

create table if not exists private.deepmap_role_audit (
    id bigint generated by default as identity primary key,
    actor_id uuid,
    target_user_id uuid not null,
    action text not null check (action in ('moderator_granted', 'moderator_revoked')),
    created_at timestamptz not null default now()
);

alter table private.deepmap_moderators enable row level security;
alter table private.deepmap_role_audit enable row level security;
revoke all on table private.deepmap_moderators from public, anon, authenticated;
revoke all on table private.deepmap_role_audit from public, anon, authenticated;

create or replace function private.is_deepmap_moderator()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
          from private.deepmap_moderators as m
         where m.user_id = (select auth.uid())
    );
$$;

create or replace function private.can_moderate_deepmap()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select private.is_deepmap_admin() or private.is_deepmap_moderator();
$$;

revoke all on function private.is_deepmap_moderator() from public, anon, authenticated;
revoke all on function private.can_moderate_deepmap() from public, anon, authenticated;
grant execute on function private.is_deepmap_moderator() to authenticated;
grant execute on function private.can_moderate_deepmap() to authenticated;

create or replace function public.get_deepmap_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
    select case
        when private.is_deepmap_admin() then 'admin'
        when private.is_deepmap_moderator() then 'moderator'
        else 'user'
    end;
$$;

revoke all on function public.get_deepmap_role() from public, anon, authenticated;
grant execute on function public.get_deepmap_role() to authenticated;

-- =========================================================
-- 2. ADMIN USER DIRECTORY / ROLE MANAGEMENT
-- =========================================================

create or replace function public.get_deepmap_users(
    p_role_filter text default 'all',
    p_search text default null,
    p_limit integer default 20,
    p_offset integer default 0
)
returns table (
    user_id uuid,
    username text,
    display_name text,
    joined_at timestamptz,
    role text,
    contribution_count bigint,
    pending_count bigint,
    approved_count bigint,
    rejected_count bigint,
    total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    if p_role_filter not in ('all', 'user', 'moderator') then
        raise exception 'INVALID_ROLE_FILTER' using errcode = 'P0001';
    end if;

    return query
    select
        p.id as user_id,
        p.username,
        p.public_display_name as display_name,
        p.joined_at,
        case
            when a.user_id is not null then 'admin'
            when m.user_id is not null then 'moderator'
            else 'user'
        end as role,
        count(s.id)::bigint as contribution_count,
        count(s.id) filter (where s.status = 'pending')::bigint as pending_count,
        count(s.id) filter (where s.status = 'approved')::bigint as approved_count,
        count(s.id) filter (where s.status = 'rejected')::bigint as rejected_count,
        count(*) over() as total_count
    from public.profiles as p
    left join private.deepmap_admins as a on a.user_id = p.id
    left join private.deepmap_moderators as m on m.user_id = p.id
    left join public.marker_submissions as s on s.submitted_by = p.id
    where
        (
            nullif(btrim(coalesce(p_search, '')), '') is null
            or p.username ilike '%' || lower(btrim(p_search)) || '%'
        )
        and (
            p_role_filter = 'all'
            or (p_role_filter = 'user' and a.user_id is null and m.user_id is null)
            or (p_role_filter = 'moderator' and a.user_id is null and m.user_id is not null)
        )
    group by p.id, p.username, p.public_display_name, p.joined_at, a.user_id, m.user_id
    order by
        case when a.user_id is not null then 0 when m.user_id is not null then 1 else 2 end,
        p.username asc
    limit greatest(1, least(coalesce(p_limit, 20), 100))
    offset greatest(coalesce(p_offset, 0), 0);
end;
$$;

revoke all on function public.get_deepmap_users(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.get_deepmap_users(text, text, integer, integer) to authenticated;

create or replace function public.set_deepmap_moderator(
    p_user_id uuid,
    p_enabled boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actor uuid := (select auth.uid());
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    if p_user_id is null or not exists (select 1 from public.profiles where id = p_user_id) then
        raise exception 'USER_NOT_FOUND' using errcode = 'P0001';
    end if;

    if exists (select 1 from private.deepmap_admins where user_id = p_user_id) then
        raise exception 'ADMIN_ROLE_PROTECTED' using errcode = 'P0001';
    end if;

    if p_enabled then
        insert into private.deepmap_moderators (user_id, created_by)
        values (p_user_id, v_actor)
        on conflict (user_id) do nothing;

        if found then
            insert into private.deepmap_role_audit (actor_id, target_user_id, action)
            values (v_actor, p_user_id, 'moderator_granted');
        end if;
    else
        delete from private.deepmap_moderators where user_id = p_user_id;

        if found then
            insert into private.deepmap_role_audit (actor_id, target_user_id, action)
            values (v_actor, p_user_id, 'moderator_revoked');
        end if;
    end if;
end;
$$;

revoke all on function public.set_deepmap_moderator(uuid, boolean) from public, anon, authenticated;
grant execute on function public.set_deepmap_moderator(uuid, boolean) to authenticated;

-- =========================================================
-- 3. SUBMISSION READ PERMISSIONS FOR MODERATORS
-- =========================================================

drop policy if exists "marker_submissions_read_own_or_admin" on public.marker_submissions;
drop policy if exists "marker_submissions_read_own_or_staff" on public.marker_submissions;
create policy "marker_submissions_read_own_or_staff"
on public.marker_submissions
for select
to authenticated
using (
    submitted_by = (select auth.uid())
    or private.can_moderate_deepmap()
);

-- =========================================================
-- 4. MODERATION RPCs — admins and moderators
-- =========================================================

create or replace function public.get_marker_submissions(
    p_game_id text,
    p_scope text default 'mine'
)
returns table (
    id bigint,
    game_id text,
    marker_id bigint,
    submission_type text,
    correction_kind text,
    status text,
    submitted_by uuid,
    submitted_username text,
    payload jsonb,
    note text,
    reviewed_by uuid,
    reviewed_username text,
    reviewed_at timestamptz,
    review_note text,
    created_at timestamptz,
    updated_at timestamptz,
    revision_count integer
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        s.id,
        s.game_id,
        s.marker_id,
        s.submission_type,
        s.correction_kind,
        s.status,
        s.submitted_by,
        submitter.username as submitted_username,
        s.payload,
        s.note,
        s.reviewed_by,
        reviewer.username as reviewed_username,
        s.reviewed_at,
        s.review_note,
        s.created_at,
        s.updated_at,
        (
            select count(*)::integer
            from private.marker_submission_revisions as r
            where r.submission_id = s.id
        ) as revision_count
    from public.marker_submissions as s
    left join public.profiles as submitter
      on submitter.id = s.submitted_by
    left join public.profiles as reviewer
      on reviewer.id = s.reviewed_by
    where s.game_id = p_game_id
      and (
          s.submitted_by = (select auth.uid())
          or (
              p_scope = 'all'
              and private.can_moderate_deepmap()
          )
      )
    order by
        case s.status when 'pending' then 0 else 1 end,
        s.updated_at desc,
        s.id desc;
$$;

create or replace function public.get_marker_submissions_page(
    p_game_id text,
    p_status text default 'pending',
    p_limit integer default 10,
    p_offset integer default 0
)
returns table (
    id bigint,
    game_id text,
    marker_id bigint,
    submission_type text,
    correction_kind text,
    status text,
    submitted_by uuid,
    submitted_username text,
    payload jsonb,
    note text,
    reviewed_by uuid,
    reviewed_username text,
    reviewed_at timestamptz,
    review_note text,
    created_at timestamptz,
    updated_at timestamptz,
    revision_count integer,
    total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not private.can_moderate_deepmap() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    if p_status not in ('pending', 'approved', 'rejected') then
        raise exception 'INVALID_STATUS' using errcode = 'P0001';
    end if;

    return query
    select
        s.id,
        s.game_id,
        s.marker_id,
        s.submission_type,
        s.correction_kind,
        s.status,
        s.submitted_by,
        submitter.username as submitted_username,
        s.payload,
        s.note,
        s.reviewed_by,
        reviewer.username as reviewed_username,
        s.reviewed_at,
        s.review_note,
        s.created_at,
        s.updated_at,
        (
            select count(*)::integer
            from private.marker_submission_revisions as r
            where r.submission_id = s.id
        ) as revision_count,
        count(*) over() as total_count
    from public.marker_submissions as s
    left join public.profiles as submitter
      on submitter.id = s.submitted_by
    left join public.profiles as reviewer
      on reviewer.id = s.reviewed_by
    where s.game_id = p_game_id
      and s.status = p_status
    order by
        case when p_status = 'pending' then s.updated_at else coalesce(s.reviewed_at, s.updated_at) end desc,
        s.id desc
    limit greatest(1, least(coalesce(p_limit, 10), 100))
    offset greatest(coalesce(p_offset, 0), 0);
end;
$$;

create or replace function public.review_marker_submission(
    p_submission_id bigint,
    p_decision text,
    p_review_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_submission public.marker_submissions%rowtype;
    v_admin uuid := (select auth.uid());
    v_marker_id bigint;
    v_slug text;
    v_image_url text;
    v_sort_order integer;
begin
    if not private.can_moderate_deepmap() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    if p_decision not in ('approved', 'rejected') then
        raise exception 'INVALID_DECISION' using errcode = 'P0001';
    end if;

    select *
      into v_submission
      from public.marker_submissions
     where id = p_submission_id
     for update;

    if not found then
        raise exception 'SUBMISSION_NOT_FOUND' using errcode = 'P0001';
    end if;

    if v_submission.status <> 'pending' then
        raise exception 'SUBMISSION_NOT_PENDING' using errcode = 'P0001';
    end if;

    if p_decision = 'rejected' then
        update public.marker_submissions
           set status = 'rejected',
               reviewed_by = v_admin,
               reviewed_at = now(),
               review_note = nullif(btrim(p_review_note), '')
         where id = p_submission_id;
        return v_submission.marker_id;
    end if;

    if v_submission.submission_type = 'create' then
        if nullif(btrim(v_submission.payload->>'category_id'), '') is null
           or nullif(btrim(v_submission.payload->>'title_en'), '') is null
           or (v_submission.payload->>'coordinate_x') is null
           or (v_submission.payload->>'coordinate_y') is null then
            raise exception 'SUBMISSION_INCOMPLETE' using errcode = 'P0001';
        end if;

        v_slug := private.deepmap_unique_marker_slug(
            v_submission.game_id,
            v_submission.payload->>'title_en'
        );

        insert into public.marcadores (
            game_id,
            map_layer,
            slug,
            category_id,
            region_id,
            title_en,
            title_pt,
            coordinate_x,
            coordinate_y,
            description_en,
            description_pt,
            video_url,
            is_published
        ) values (
            v_submission.game_id,
            coalesce(nullif(btrim(v_submission.payload->>'map_layer'), ''), 'surface'),
            v_slug,
            btrim(v_submission.payload->>'category_id'),
            nullif(btrim(v_submission.payload->>'region_id'), ''),
            btrim(v_submission.payload->>'title_en'),
            coalesce(nullif(btrim(v_submission.payload->>'title_pt'), ''), btrim(v_submission.payload->>'title_en')),
            (v_submission.payload->>'coordinate_x')::double precision,
            (v_submission.payload->>'coordinate_y')::double precision,
            nullif(btrim(v_submission.payload->>'description_en'), ''),
            nullif(btrim(v_submission.payload->>'description_pt'), ''),
            nullif(btrim(v_submission.payload->>'video_url'), ''),
            true
        )
        returning id into v_marker_id;

        -- Replace trigger attribution with the community author + current approver.
        insert into private.marker_editor_audit as audit (
            marker_id,
            created_by,
            created_at,
            updated_by,
            updated_at,
            published_by,
            published_at,
            approved_by,
            approved_at
        ) values (
            v_marker_id,
            v_submission.submitted_by,
            now(),
            v_submission.submitted_by,
            now(),
            v_admin,
            now(),
            v_admin,
            now()
        )
        on conflict (marker_id) do update
        set
            created_by = excluded.created_by,
            created_at = coalesce(audit.created_at, excluded.created_at),
            updated_by = excluded.updated_by,
            updated_at = excluded.updated_at,
            published_by = excluded.published_by,
            published_at = coalesce(audit.published_at, excluded.published_at),
            approved_by = excluded.approved_by,
            approved_at = excluded.approved_at;

        v_image_url := nullif(btrim(v_submission.payload->>'image_url'), '');
        if v_image_url is not null then
            insert into public.marker_images (
                marker_id,
                source,
                image_ref,
                sort_order,
                is_cover
            ) values (
                v_marker_id,
                case when v_image_url like '/%' then 'static' else 'external' end,
                v_image_url,
                10,
                true
            );
        end if;

        update public.marker_submissions
           set marker_id = v_marker_id
         where id = p_submission_id;

    else
        v_marker_id := v_submission.marker_id;

        if not exists (
            select 1 from public.marcadores as m
            where m.id = v_marker_id
              and m.game_id = v_submission.game_id
        ) then
            raise exception 'TARGET_MARKER_NOT_FOUND' using errcode = 'P0001';
        end if;

        if v_submission.correction_kind = 'text' then
            update public.marcadores
               set title_en = case when v_submission.payload ? 'title_en' then coalesce(nullif(btrim(v_submission.payload->>'title_en'), ''), title_en) else title_en end,
                   title_pt = case when v_submission.payload ? 'title_pt' then coalesce(nullif(btrim(v_submission.payload->>'title_pt'), ''), title_pt) else title_pt end,
                   region_id = case when v_submission.payload ? 'region_id' then nullif(btrim(v_submission.payload->>'region_id'), '') else region_id end,
                   description_en = case when v_submission.payload ? 'description_en' then nullif(btrim(v_submission.payload->>'description_en'), '') else description_en end,
                   description_pt = case when v_submission.payload ? 'description_pt' then nullif(btrim(v_submission.payload->>'description_pt'), '') else description_pt end,
                   video_url = case when v_submission.payload ? 'video_url' then nullif(btrim(v_submission.payload->>'video_url'), '') else video_url end
             where id = v_marker_id;

        elsif v_submission.correction_kind = 'location' then
            update public.marcadores
               set coordinate_x = coalesce(nullif(v_submission.payload->>'coordinate_x', '')::double precision, coordinate_x),
                   coordinate_y = coalesce(nullif(v_submission.payload->>'coordinate_y', '')::double precision, coordinate_y)
             where id = v_marker_id;

        elsif v_submission.correction_kind = 'image' then
            v_image_url := nullif(btrim(v_submission.payload->>'image_url'), '');

            if coalesce(v_submission.payload->>'image_action', 'add') = 'report' then
                if nullif(v_submission.payload->>'target_image_id', '') is null then
                    raise exception 'IMAGE_TARGET_REQUIRED' using errcode = 'P0001';
                end if;

                delete from public.marker_images
                 where id = (v_submission.payload->>'target_image_id')::bigint
                   and marker_id = v_marker_id;
            elsif v_image_url is not null then
                select coalesce(max(mi.sort_order), 0) + 10
                  into v_sort_order
                  from public.marker_images as mi
                 where mi.marker_id = v_marker_id;

                insert into public.marker_images (
                    marker_id,
                    source,
                    image_ref,
                    sort_order,
                    is_cover
                ) values (
                    v_marker_id,
                    case when v_image_url like '/%' then 'static' else 'external' end,
                    v_image_url,
                    v_sort_order,
                    false
                );
            end if;
        end if;

        -- Only accepted content changes renew public modification/approval attribution.
        if v_submission.correction_kind in ('text', 'location', 'image') then
            insert into private.marker_editor_audit as audit (
                marker_id,
                updated_by,
                updated_at,
                approved_by,
                approved_at
            ) values (
                v_marker_id,
                v_submission.submitted_by,
                now(),
                v_admin,
                now()
            )
            on conflict (marker_id) do update
            set
                updated_by = excluded.updated_by,
                updated_at = excluded.updated_at,
                approved_by = excluded.approved_by,
                approved_at = excluded.approved_at;
        end if;
    end if;

    update public.marker_submissions
       set status = 'approved',
           reviewed_by = v_admin,
           reviewed_at = now(),
           review_note = nullif(btrim(p_review_note), '')
     where id = p_submission_id;

    return v_marker_id;
end;
$$;

create or replace function public.review_marker_submission_v2(
    p_submission_id bigint,
    p_decision text,
    p_review_note text default null,
    p_payload_override jsonb default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_admin uuid := (select auth.uid());
    v_marker_id bigint;
    v_payload jsonb;
begin
    if not private.can_moderate_deepmap() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    if p_decision not in ('approved', 'rejected') then
        raise exception 'INVALID_DECISION' using errcode = 'P0001';
    end if;

    if p_decision = 'approved' and p_payload_override is not null then
        update public.marker_submissions
           set payload = p_payload_override
         where id = p_submission_id
           and status = 'pending';

        if not found then
            raise exception 'SUBMISSION_NOT_PENDING' using errcode = 'P0001';
        end if;
    end if;

    v_marker_id := public.review_marker_submission(
        p_submission_id,
        p_decision,
        p_review_note
    );

    if p_decision <> 'approved' or p_payload_override is null or v_marker_id is null then
        return v_marker_id;
    end if;

    v_payload := p_payload_override;

    if nullif(btrim(v_payload->>'category_id'), '') is null
       or nullif(btrim(v_payload->>'title_en'), '') is null
       or (v_payload->>'coordinate_x') is null
       or (v_payload->>'coordinate_y') is null then
        raise exception 'SUBMISSION_INCOMPLETE' using errcode = 'P0001';
    end if;

    -- Apply the moderator's final reviewed version as one complete marker state.
    update public.marcadores
       set map_layer = coalesce(nullif(btrim(v_payload->>'map_layer'), ''), map_layer),
           category_id = btrim(v_payload->>'category_id'),
           region_id = nullif(btrim(v_payload->>'region_id'), ''),
           title_en = btrim(v_payload->>'title_en'),
           title_pt = coalesce(nullif(btrim(v_payload->>'title_pt'), ''), btrim(v_payload->>'title_en')),
           coordinate_x = (v_payload->>'coordinate_x')::double precision,
           coordinate_y = (v_payload->>'coordinate_y')::double precision,
           description_en = nullif(btrim(v_payload->>'description_en'), ''),
           description_pt = nullif(btrim(v_payload->>'description_pt'), ''),
           video_url = nullif(btrim(v_payload->>'video_url'), '')
     where id = v_marker_id;

    perform private.deepmap_replace_quick_marker_content(
        v_marker_id,
        v_payload->'content_items'
    );

    -- The marker audit trigger records the moderator as last editor when the
    -- reviewed version differs from the submitted one. Re-stamp approval after
    -- that update so the admin audit remains complete.
    update private.marker_editor_audit
       set approved_by = v_admin,
           approved_at = now()
     where marker_id = v_marker_id;

    return v_marker_id;
end;
$$;

-- Restore explicit execute grants after replacing the functions.
revoke all on function public.get_marker_submissions(text, text) from public, anon, authenticated;
grant execute on function public.get_marker_submissions(text, text) to authenticated;

revoke all on function public.get_marker_submissions_page(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.get_marker_submissions_page(text, text, integer, integer) to authenticated;

revoke all on function public.review_marker_submission(bigint, text, text) from public, anon, authenticated;
grant execute on function public.review_marker_submission(bigint, text, text) to authenticated;

revoke all on function public.review_marker_submission_v2(bigint, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.review_marker_submission_v2(bigint, text, text, jsonb) to authenticated;

commit;
