-- DeepMap — Community marker contributions + moderation
-- Users can submit new markers and corrections without direct write access to public.marcadores.
-- Admins/moderators review submissions; accepted changes are applied server-side.

begin;

create schema if not exists private;

-- =========================================================
-- 1. MARKER SUBMISSIONS
-- =========================================================

create table if not exists public.marker_submissions (
    id bigint generated by default as identity primary key,

    game_id text not null,
    marker_id bigint references public.marcadores(id) on delete cascade,

    submission_type text not null
        check (submission_type in ('create', 'correction')),

    correction_kind text
        check (
            correction_kind is null
            or correction_kind in ('text', 'location', 'image', 'other')
        ),

    status text not null default 'pending'
        check (status in ('pending', 'approved', 'rejected', 'cancelled')),

    -- UUID kept even if the account is later deleted; public profile resolution can then fall back to an anonymised author.
    submitted_by uuid not null,

    payload jsonb not null default '{}'::jsonb,
    note text,

    reviewed_by uuid,
    reviewed_at timestamptz,
    review_note text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint marker_submissions_target_required
        check (
            submission_type <> 'correction'
            or marker_id is not null
        )
);

create index if not exists marker_submissions_game_status_idx
    on public.marker_submissions (game_id, status, created_at desc);

create index if not exists marker_submissions_user_status_idx
    on public.marker_submissions (submitted_by, status, created_at desc);

create index if not exists marker_submissions_marker_idx
    on public.marker_submissions (marker_id, created_at desc)
    where marker_id is not null;

-- =========================================================
-- 2. INTERNAL REVISION HISTORY
-- =========================================================

create table if not exists private.marker_submission_revisions (
    id bigint generated by default as identity primary key,
    submission_id bigint not null
        references public.marker_submissions(id)
        on delete cascade,
    revision_no integer not null,
    edited_by uuid,
    payload jsonb not null default '{}'::jsonb,
    note text,
    created_at timestamptz not null default now(),
    unique (submission_id, revision_no)
);

alter table private.marker_submission_revisions enable row level security;
revoke all on table private.marker_submission_revisions
from public, anon, authenticated;

create or replace function private.deepmap_capture_submission_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_revision integer;
begin
    if tg_op = 'UPDATE'
       and new.payload is not distinct from old.payload
       and new.note is not distinct from old.note
       and new.correction_kind is not distinct from old.correction_kind then
        return new;
    end if;

    select coalesce(max(r.revision_no), 0) + 1
      into v_revision
      from private.marker_submission_revisions as r
     where r.submission_id = new.id;

    insert into private.marker_submission_revisions (
        submission_id,
        revision_no,
        edited_by,
        payload,
        note
    ) values (
        new.id,
        v_revision,
        (select auth.uid()),
        new.payload,
        new.note
    );

    return new;
end;
$$;

revoke all on function private.deepmap_capture_submission_revision()
from public, anon, authenticated;

drop trigger if exists deepmap_marker_submission_revision
on public.marker_submissions;

create trigger deepmap_marker_submission_revision
after insert or update of payload, note, correction_kind
on public.marker_submissions
for each row
execute function private.deepmap_capture_submission_revision();

-- =========================================================
-- 3. UPDATED_AT
-- =========================================================

create or replace function private.deepmap_touch_submission_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

revoke all on function private.deepmap_touch_submission_updated_at()
from public, anon, authenticated;

drop trigger if exists deepmap_marker_submissions_touch_updated_at
on public.marker_submissions;

create trigger deepmap_marker_submissions_touch_updated_at
before update on public.marker_submissions
for each row
execute function private.deepmap_touch_submission_updated_at();

-- =========================================================
-- 4. RLS / USER PERMISSIONS
-- =========================================================

alter table public.marker_submissions enable row level security;

revoke all on table public.marker_submissions
from public, anon, authenticated;

-- Users may read their own submissions. Admins can read every submission.
grant select on table public.marker_submissions to authenticated;

-- Users may create submissions and edit only the user-editable columns while pending.
grant insert (game_id, marker_id, submission_type, correction_kind, status, submitted_by, payload, note)
on public.marker_submissions to authenticated;
grant update (payload, note, correction_kind)
on public.marker_submissions to authenticated;

grant usage, select on sequence public.marker_submissions_id_seq to authenticated;

drop policy if exists "marker_submissions_read_own_or_admin"
on public.marker_submissions;

create policy "marker_submissions_read_own_or_admin"
on public.marker_submissions
for select
to authenticated
using (
    submitted_by = (select auth.uid())
    or private.is_deepmap_admin()
);

drop policy if exists "marker_submissions_insert_own"
on public.marker_submissions;

create policy "marker_submissions_insert_own"
on public.marker_submissions
for insert
to authenticated
with check (
    submitted_by = (select auth.uid())
    and status = 'pending'
    and reviewed_by is null
    and reviewed_at is null
    and review_note is null
);

drop policy if exists "marker_submissions_update_own_pending"
on public.marker_submissions;

create policy "marker_submissions_update_own_pending"
on public.marker_submissions
for update
to authenticated
using (
    submitted_by = (select auth.uid())
    and status = 'pending'
)
with check (
    submitted_by = (select auth.uid())
    and status = 'pending'
);

-- =========================================================
-- 5. AUDIT V2 — CREATOR / MODIFIER / APPROVER
-- =========================================================

alter table private.marker_editor_audit
    add column if not exists approved_by uuid,
    add column if not exists approved_at timestamptz;

create or replace function private.deepmap_stamp_marker_audit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := (select auth.uid());
    v_content_changed boolean := false;
begin
    if tg_op = 'INSERT' then
        insert into private.marker_editor_audit as audit (
            marker_id,
            created_by,
            created_at,
            updated_by,
            updated_at,
            published_by,
            published_at,
            approved_by,
            approved_at
        ) values (
            new.id,
            v_user_id,
            now(),
            v_user_id,
            now(),
            case when new.is_published then v_user_id else null end,
            case when new.is_published then now() else null end,
            null,
            null
        )
        on conflict (marker_id) do update
        set
            updated_by = excluded.updated_by,
            updated_at = excluded.updated_at,
            published_by = case
                when new.is_published then coalesce(audit.published_by, excluded.published_by)
                else audit.published_by
            end,
            published_at = case
                when new.is_published then coalesce(audit.published_at, excluded.published_at)
                else audit.published_at
            end,
            approved_by = null,
            approved_at = null;

        return new;
    end if;

    -- Publication toggles alone do not count as a content modification.
    v_content_changed :=
        (to_jsonb(new) - 'updated_at' - 'is_published')
        is distinct from
        (to_jsonb(old) - 'updated_at' - 'is_published');

    insert into private.marker_editor_audit as audit (
        marker_id,
        created_by,
        created_at,
        updated_by,
        updated_at,
        published_by,
        published_at,
        approved_by,
        approved_at
    ) values (
        new.id,
        null,
        null,
        case when v_content_changed then v_user_id else null end,
        case when v_content_changed then now() else null end,
        case when new.is_published then v_user_id else null end,
        case when new.is_published then now() else null end,
        null,
        null
    )
    on conflict (marker_id) do update
    set
        updated_by = case
            when v_content_changed then v_user_id
            else audit.updated_by
        end,
        updated_at = case
            when v_content_changed then now()
            else audit.updated_at
        end,
        published_by = case
            when new.is_published
                 and (
                     old.is_published = false
                     or old.is_published is null
                     or audit.published_by is null
                 )
                then v_user_id
            else audit.published_by
        end,
        published_at = case
            when new.is_published
                 and (
                     old.is_published = false
                     or old.is_published is null
                     or audit.published_at is null
                 )
                then now()
            else audit.published_at
        end,
        -- Any direct content edit creates a new version that has not passed moderation.
        approved_by = case
            when v_content_changed then null
            else audit.approved_by
        end,
        approved_at = case
            when v_content_changed then null
            else audit.approved_at
        end;

    return new;
end;
$$;

revoke all on function private.deepmap_stamp_marker_audit()
from public, anon, authenticated;

-- Existing trigger keeps using the replaced function.

-- Admin audit RPC now includes the latest approval.
-- DROP is required because PostgreSQL does not allow CREATE OR REPLACE to change a TABLE return shape.
drop function if exists public.get_marker_editor_audit(text);

create function public.get_marker_editor_audit(p_game_id text)
returns table (
    marker_id bigint,
    created_by uuid,
    created_username text,
    created_at timestamptz,
    updated_by uuid,
    updated_username text,
    updated_at timestamptz,
    published_by uuid,
    published_username text,
    published_at timestamptz,
    approved_by uuid,
    approved_username text,
    approved_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        a.marker_id,
        a.created_by,
        pc.username as created_username,
        a.created_at,
        a.updated_by,
        pu.username as updated_username,
        a.updated_at,
        a.published_by,
        pp.username as published_username,
        a.published_at,
        a.approved_by,
        pa.username as approved_username,
        a.approved_at
    from private.marker_editor_audit as a
    join public.marcadores as m
      on m.id = a.marker_id
    left join public.profiles as pc
      on pc.id = a.created_by
    left join public.profiles as pu
      on pu.id = a.updated_by
    left join public.profiles as pp
      on pp.id = a.published_by
    left join public.profiles as pa
      on pa.id = a.approved_by
    where m.game_id = p_game_id
      and private.is_deepmap_admin();
$$;

revoke all on function public.get_marker_editor_audit(text)
from public, anon, authenticated;

grant execute on function public.get_marker_editor_audit(text)
to authenticated;

-- Public attribution contains usernames only. UUIDs and audit dates stay private.
drop function if exists public.get_public_marker_attribution(text);

create function public.get_public_marker_attribution(p_game_id text)
returns table (
    marker_id bigint,
    published_username text,
    modified_username text,
    approved_username text
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        a.marker_id,
        creator.username as published_username,
        case
            when a.updated_by is not null
             and a.updated_at is not null
             and (a.created_at is null or a.updated_at > a.created_at)
            then modifier.username
            else null
        end as modified_username,
        approver.username as approved_username
    from private.marker_editor_audit as a
    join public.marcadores as m
      on m.id = a.marker_id
    left join public.profiles as creator
      on creator.id = a.created_by
    left join public.profiles as modifier
      on modifier.id = a.updated_by
    left join public.profiles as approver
      on approver.id = a.approved_by
    where m.game_id = p_game_id
      and m.is_published = true;
$$;

revoke all on function public.get_public_marker_attribution(text)
from public, anon, authenticated;

grant execute on function public.get_public_marker_attribution(text)
to anon, authenticated;

-- =========================================================
-- 6. SUBMISSION LIST RPC
-- =========================================================

create or replace function public.get_marker_submissions(
    p_game_id text,
    p_scope text default 'mine'
)
returns table (
    id bigint,
    game_id text,
    marker_id bigint,
    submission_type text,
    correction_kind text,
    status text,
    submitted_by uuid,
    submitted_username text,
    payload jsonb,
    note text,
    reviewed_by uuid,
    reviewed_username text,
    reviewed_at timestamptz,
    review_note text,
    created_at timestamptz,
    updated_at timestamptz,
    revision_count integer
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        s.id,
        s.game_id,
        s.marker_id,
        s.submission_type,
        s.correction_kind,
        s.status,
        s.submitted_by,
        submitter.username as submitted_username,
        s.payload,
        s.note,
        s.reviewed_by,
        reviewer.username as reviewed_username,
        s.reviewed_at,
        s.review_note,
        s.created_at,
        s.updated_at,
        (
            select count(*)::integer
            from private.marker_submission_revisions as r
            where r.submission_id = s.id
        ) as revision_count
    from public.marker_submissions as s
    left join public.profiles as submitter
      on submitter.id = s.submitted_by
    left join public.profiles as reviewer
      on reviewer.id = s.reviewed_by
    where s.game_id = p_game_id
      and (
          s.submitted_by = (select auth.uid())
          or (
              p_scope = 'all'
              and private.is_deepmap_admin()
          )
      )
    order by
        case s.status when 'pending' then 0 else 1 end,
        s.updated_at desc,
        s.id desc;
$$;

revoke all on function public.get_marker_submissions(text, text)
from public, anon, authenticated;

grant execute on function public.get_marker_submissions(text, text)
to authenticated;

-- =========================================================
-- 7. CANCEL OWN PENDING SUBMISSION
-- =========================================================

create or replace function public.cancel_marker_submission(p_submission_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    update public.marker_submissions
       set status = 'cancelled',
           updated_at = now()
     where id = p_submission_id
       and submitted_by = (select auth.uid())
       and status = 'pending';

    if not found then
        raise exception 'SUBMISSION_NOT_CANCELLABLE' using errcode = 'P0001';
    end if;
end;
$$;

revoke all on function public.cancel_marker_submission(bigint)
from public, anon, authenticated;

grant execute on function public.cancel_marker_submission(bigint)
to authenticated;

-- =========================================================
-- 8. SLUG HELPERS FOR APPROVED USER SUBMISSIONS
-- =========================================================

create or replace function private.deepmap_slugify(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
    select nullif(
        trim(both '-' from regexp_replace(lower(coalesce(p_value, '')), '[^a-z0-9]+', '-', 'g')),
        ''
    );
$$;

revoke all on function private.deepmap_slugify(text)
from public, anon, authenticated;

create or replace function private.deepmap_unique_marker_slug(
    p_game_id text,
    p_title text
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_base text;
    v_candidate text;
    v_suffix integer := 1;
begin
    v_base := left(coalesce(private.deepmap_slugify(p_title), 'marker'), 70);
    v_candidate := v_base;

    while exists (
        select 1
        from public.marcadores as m
        where m.game_id = p_game_id
          and m.slug = v_candidate
    ) loop
        v_suffix := v_suffix + 1;
        v_candidate := left(v_base, greatest(1, 78 - length(v_suffix::text))) || '-' || v_suffix::text;
    end loop;

    return v_candidate;
end;
$$;

revoke all on function private.deepmap_unique_marker_slug(text, text)
from public, anon, authenticated;

-- =========================================================
-- 9. ADMIN REVIEW / APPLY
-- =========================================================

create or replace function public.review_marker_submission(
    p_submission_id bigint,
    p_decision text,
    p_review_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_submission public.marker_submissions%rowtype;
    v_admin uuid := (select auth.uid());
    v_marker_id bigint;
    v_slug text;
    v_image_url text;
    v_sort_order integer;
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    if p_decision not in ('approved', 'rejected') then
        raise exception 'INVALID_DECISION' using errcode = 'P0001';
    end if;

    select *
      into v_submission
      from public.marker_submissions
     where id = p_submission_id
     for update;

    if not found then
        raise exception 'SUBMISSION_NOT_FOUND' using errcode = 'P0001';
    end if;

    if v_submission.status <> 'pending' then
        raise exception 'SUBMISSION_NOT_PENDING' using errcode = 'P0001';
    end if;

    if p_decision = 'rejected' then
        update public.marker_submissions
           set status = 'rejected',
               reviewed_by = v_admin,
               reviewed_at = now(),
               review_note = nullif(btrim(p_review_note), '')
         where id = p_submission_id;
        return v_submission.marker_id;
    end if;

    if v_submission.submission_type = 'create' then
        if nullif(btrim(v_submission.payload->>'category_id'), '') is null
           or nullif(btrim(v_submission.payload->>'title_en'), '') is null
           or nullif(btrim(v_submission.payload->>'title_pt'), '') is null
           or (v_submission.payload->>'coordinate_x') is null
           or (v_submission.payload->>'coordinate_y') is null then
            raise exception 'SUBMISSION_INCOMPLETE' using errcode = 'P0001';
        end if;

        v_slug := private.deepmap_unique_marker_slug(
            v_submission.game_id,
            v_submission.payload->>'title_en'
        );

        insert into public.marcadores (
            game_id,
            map_layer,
            slug,
            category_id,
            region_id,
            title_en,
            title_pt,
            coordinate_x,
            coordinate_y,
            description_en,
            description_pt,
            video_url,
            is_published
        ) values (
            v_submission.game_id,
            coalesce(nullif(btrim(v_submission.payload->>'map_layer'), ''), 'surface'),
            v_slug,
            btrim(v_submission.payload->>'category_id'),
            nullif(btrim(v_submission.payload->>'region_id'), ''),
            btrim(v_submission.payload->>'title_en'),
            btrim(v_submission.payload->>'title_pt'),
            (v_submission.payload->>'coordinate_x')::double precision,
            (v_submission.payload->>'coordinate_y')::double precision,
            nullif(btrim(v_submission.payload->>'description_en'), ''),
            nullif(btrim(v_submission.payload->>'description_pt'), ''),
            nullif(btrim(v_submission.payload->>'video_url'), ''),
            true
        )
        returning id into v_marker_id;

        -- Replace trigger attribution with the community author + current approver.
        insert into private.marker_editor_audit as audit (
            marker_id,
            created_by,
            created_at,
            updated_by,
            updated_at,
            published_by,
            published_at,
            approved_by,
            approved_at
        ) values (
            v_marker_id,
            v_submission.submitted_by,
            now(),
            v_submission.submitted_by,
            now(),
            v_admin,
            now(),
            v_admin,
            now()
        )
        on conflict (marker_id) do update
        set
            created_by = excluded.created_by,
            created_at = coalesce(audit.created_at, excluded.created_at),
            updated_by = excluded.updated_by,
            updated_at = excluded.updated_at,
            published_by = excluded.published_by,
            published_at = coalesce(audit.published_at, excluded.published_at),
            approved_by = excluded.approved_by,
            approved_at = excluded.approved_at;

        v_image_url := nullif(btrim(v_submission.payload->>'image_url'), '');
        if v_image_url is not null then
            insert into public.marker_images (
                marker_id,
                source,
                image_ref,
                sort_order,
                is_cover
            ) values (
                v_marker_id,
                case when v_image_url like '/%' then 'static' else 'external' end,
                v_image_url,
                10,
                true
            );
        end if;

        update public.marker_submissions
           set marker_id = v_marker_id
         where id = p_submission_id;

    else
        v_marker_id := v_submission.marker_id;

        if not exists (
            select 1 from public.marcadores as m
            where m.id = v_marker_id
              and m.game_id = v_submission.game_id
        ) then
            raise exception 'TARGET_MARKER_NOT_FOUND' using errcode = 'P0001';
        end if;

        if v_submission.correction_kind = 'text' then
            update public.marcadores
               set title_en = case when v_submission.payload ? 'title_en' then coalesce(nullif(btrim(v_submission.payload->>'title_en'), ''), title_en) else title_en end,
                   title_pt = case when v_submission.payload ? 'title_pt' then coalesce(nullif(btrim(v_submission.payload->>'title_pt'), ''), title_pt) else title_pt end,
                   region_id = case when v_submission.payload ? 'region_id' then nullif(btrim(v_submission.payload->>'region_id'), '') else region_id end,
                   description_en = case when v_submission.payload ? 'description_en' then nullif(btrim(v_submission.payload->>'description_en'), '') else description_en end,
                   description_pt = case when v_submission.payload ? 'description_pt' then nullif(btrim(v_submission.payload->>'description_pt'), '') else description_pt end,
                   video_url = case when v_submission.payload ? 'video_url' then nullif(btrim(v_submission.payload->>'video_url'), '') else video_url end
             where id = v_marker_id;

        elsif v_submission.correction_kind = 'location' then
            update public.marcadores
               set coordinate_x = coalesce(nullif(v_submission.payload->>'coordinate_x', '')::double precision, coordinate_x),
                   coordinate_y = coalesce(nullif(v_submission.payload->>'coordinate_y', '')::double precision, coordinate_y)
             where id = v_marker_id;

        elsif v_submission.correction_kind = 'image' then
            v_image_url := nullif(btrim(v_submission.payload->>'image_url'), '');

            if coalesce(v_submission.payload->>'image_action', 'add') = 'report' then
                if nullif(v_submission.payload->>'target_image_id', '') is null then
                    raise exception 'IMAGE_TARGET_REQUIRED' using errcode = 'P0001';
                end if;

                delete from public.marker_images
                 where id = (v_submission.payload->>'target_image_id')::bigint
                   and marker_id = v_marker_id;
            elsif v_image_url is not null then
                select coalesce(max(mi.sort_order), 0) + 10
                  into v_sort_order
                  from public.marker_images as mi
                 where mi.marker_id = v_marker_id;

                insert into public.marker_images (
                    marker_id,
                    source,
                    image_ref,
                    sort_order,
                    is_cover
                ) values (
                    v_marker_id,
                    case when v_image_url like '/%' then 'static' else 'external' end,
                    v_image_url,
                    v_sort_order,
                    false
                );
            end if;
        end if;

        -- Only accepted content changes renew public modification/approval attribution.
        if v_submission.correction_kind in ('text', 'location', 'image') then
            insert into private.marker_editor_audit as audit (
                marker_id,
                updated_by,
                updated_at,
                approved_by,
                approved_at
            ) values (
                v_marker_id,
                v_submission.submitted_by,
                now(),
                v_admin,
                now()
            )
            on conflict (marker_id) do update
            set
                updated_by = excluded.updated_by,
                updated_at = excluded.updated_at,
                approved_by = excluded.approved_by,
                approved_at = excluded.approved_at;
        end if;
    end if;

    update public.marker_submissions
       set status = 'approved',
           reviewed_by = v_admin,
           reviewed_at = now(),
           review_note = nullif(btrim(p_review_note), '')
     where id = p_submission_id;

    return v_marker_id;
end;
$$;

revoke all on function public.review_marker_submission(bigint, text, text)
from public, anon, authenticated;

grant execute on function public.review_marker_submission(bigint, text, text)
to authenticated;

commit;
