-- DeepMap — moderation review editor, creator-only public attribution and in-app notifications
-- Run after map-community-contributions.sql, map-community-content-items.sql and map-community-moderation-history.sql.

begin;

-- =========================================================
-- 1. IN-APP NOTIFICATIONS
-- =========================================================

create table if not exists public.user_notifications (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    game_id text not null,
    submission_id bigint references public.marker_submissions(id) on delete set null,
    marker_id bigint references public.marcadores(id) on delete set null,
    submission_type text not null check (submission_type in ('create', 'correction')),
    decision text not null check (decision in ('approved', 'rejected')),
    review_note text,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists user_notifications_user_created_idx
    on public.user_notifications (user_id, created_at desc);

create index if not exists user_notifications_user_unread_idx
    on public.user_notifications (user_id, created_at desc)
    where is_read = false;

create unique index if not exists user_notifications_submission_decision_uidx
    on public.user_notifications (user_id, submission_id, decision)
    where submission_id is not null;

alter table public.user_notifications enable row level security;
revoke all on table public.user_notifications from public, anon, authenticated;
grant select on table public.user_notifications to authenticated;
grant update (is_read) on table public.user_notifications to authenticated;

drop policy if exists "user_notifications_read_own" on public.user_notifications;
create policy "user_notifications_read_own"
on public.user_notifications
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "user_notifications_update_own" on public.user_notifications;
create policy "user_notifications_update_own"
on public.user_notifications
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

-- Keep the unread badge live while the contributor is on the site.
do $$
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (
           select 1
             from pg_publication_tables
            where pubname = 'supabase_realtime'
              and schemaname = 'public'
              and tablename = 'user_notifications'
       ) then
        execute 'alter publication supabase_realtime add table public.user_notifications';
    end if;
end
$$;

create or replace function private.deepmap_notify_submission_review()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if old.status = 'pending'
       and new.status in ('approved', 'rejected') then
        insert into public.user_notifications (
            user_id,
            game_id,
            submission_id,
            marker_id,
            submission_type,
            decision,
            review_note
        ) values (
            new.submitted_by,
            new.game_id,
            new.id,
            new.marker_id,
            new.submission_type,
            new.status,
            new.review_note
        )
        on conflict (user_id, submission_id, decision)
        where submission_id is not null
        do update set
            marker_id = excluded.marker_id,
            review_note = excluded.review_note,
            created_at = now(),
            is_read = false;
    end if;

    return new;
end;
$$;

revoke all on function private.deepmap_notify_submission_review()
from public, anon, authenticated;

drop trigger if exists deepmap_notify_submission_review
on public.marker_submissions;

create trigger deepmap_notify_submission_review
after update of status, marker_id, review_note
on public.marker_submissions
for each row
when (old.status is distinct from new.status)
execute function private.deepmap_notify_submission_review();

-- =========================================================
-- 2. PUBLIC ATTRIBUTION: CREATOR ONLY
-- =========================================================

-- The public popup never exposes modifier/approver audit information.
-- The existing front-end field keeps the historical published_username name
-- for compatibility, but its value is now the original creator.
drop function if exists public.get_public_marker_attribution(text);

create function public.get_public_marker_attribution(p_game_id text)
returns table (
    marker_id bigint,
    published_username text
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        a.marker_id,
        creator.username as published_username
    from private.marker_editor_audit as a
    join public.marcadores as m
      on m.id = a.marker_id
    left join public.profiles as creator
      on creator.id = a.created_by
    where m.game_id = p_game_id
      and m.is_published = true;
$$;

revoke all on function public.get_public_marker_attribution(text)
from public, anon, authenticated;

grant execute on function public.get_public_marker_attribution(text)
to anon, authenticated;

-- =========================================================
-- 3. QUICK CONTENT REPLACEMENT USED BY MODERATION
-- =========================================================

create or replace function private.deepmap_replace_quick_marker_content(
    p_marker_id bigint,
    p_items jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_item jsonb;
    v_type text;
    v_text_en text;
    v_text_pt text;
    v_section_id bigint;
    v_sort integer := 0;
begin
    delete from public.marker_sections
     where marker_id = p_marker_id
       and metadata->>'editor' = 'quick-content-v1';

    if p_items is null or jsonb_typeof(p_items) <> 'array' then
        return;
    end if;

    for v_item in select value from jsonb_array_elements(p_items)
    loop
        v_type := coalesce(nullif(btrim(v_item->>'type'), ''), 'note');
        if v_type not in ('npc', 'item', 'reward', 'requirement', 'note') then
            v_type := 'note';
        end if;

        v_text_en := nullif(btrim(v_item->>'text_en'), '');
        v_text_pt := nullif(btrim(v_item->>'text_pt'), '');
        if v_text_en is null and v_text_pt is null then
            continue;
        end if;

        v_sort := v_sort + 10;

        insert into public.marker_sections (
            marker_id, section_type, title_en, title_pt,
            sort_order, is_collapsible, metadata
        ) values (
            p_marker_id,
            v_type,
            case v_type when 'npc' then 'NPC' when 'item' then 'Item' when 'reward' then 'Reward' when 'requirement' then 'Requirement' else 'Note' end,
            case v_type when 'npc' then 'NPC' when 'item' then 'Item' when 'reward' then 'Recompensa' when 'requirement' then 'Requisito' else 'Nota' end,
            v_sort,
            true,
            jsonb_build_object('editor', 'quick-content-v1', 'source', 'moderation-v2')
        ) returning id into v_section_id;

        insert into public.marker_section_rows (
            section_id, row_type, text_en, text_pt, sort_order, metadata
        ) values (
            v_section_id,
            'text',
            v_text_en,
            v_text_pt,
            10,
            jsonb_build_object('editor', 'quick-content-v1', 'source', 'moderation-v2')
        );
    end loop;
end;
$$;

revoke all on function private.deepmap_replace_quick_marker_content(bigint, jsonb)
from public, anon, authenticated;

-- =========================================================
-- 4. FULL MODERATION REVIEW
-- =========================================================

create or replace function public.review_marker_submission_v2(
    p_submission_id bigint,
    p_decision text,
    p_review_note text default null,
    p_payload_override jsonb default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_admin uuid := (select auth.uid());
    v_marker_id bigint;
    v_payload jsonb;
begin
    if not private.is_deepmap_admin() then
        raise exception 'ADMIN_REQUIRED' using errcode = 'P0001';
    end if;

    if p_decision not in ('approved', 'rejected') then
        raise exception 'INVALID_DECISION' using errcode = 'P0001';
    end if;

    if p_decision = 'approved' and p_payload_override is not null then
        update public.marker_submissions
           set payload = p_payload_override
         where id = p_submission_id
           and status = 'pending';

        if not found then
            raise exception 'SUBMISSION_NOT_PENDING' using errcode = 'P0001';
        end if;
    end if;

    v_marker_id := public.review_marker_submission(
        p_submission_id,
        p_decision,
        p_review_note
    );

    if p_decision <> 'approved' or p_payload_override is null or v_marker_id is null then
        return v_marker_id;
    end if;

    v_payload := p_payload_override;

    if nullif(btrim(v_payload->>'category_id'), '') is null
       or nullif(btrim(v_payload->>'title_en'), '') is null
       or (v_payload->>'coordinate_x') is null
       or (v_payload->>'coordinate_y') is null then
        raise exception 'SUBMISSION_INCOMPLETE' using errcode = 'P0001';
    end if;

    -- Apply the moderator's final reviewed version as one complete marker state.
    update public.marcadores
       set map_layer = coalesce(nullif(btrim(v_payload->>'map_layer'), ''), map_layer),
           category_id = btrim(v_payload->>'category_id'),
           region_id = nullif(btrim(v_payload->>'region_id'), ''),
           title_en = btrim(v_payload->>'title_en'),
           title_pt = coalesce(nullif(btrim(v_payload->>'title_pt'), ''), btrim(v_payload->>'title_en')),
           coordinate_x = (v_payload->>'coordinate_x')::double precision,
           coordinate_y = (v_payload->>'coordinate_y')::double precision,
           description_en = nullif(btrim(v_payload->>'description_en'), ''),
           description_pt = nullif(btrim(v_payload->>'description_pt'), ''),
           video_url = nullif(btrim(v_payload->>'video_url'), '')
     where id = v_marker_id;

    perform private.deepmap_replace_quick_marker_content(
        v_marker_id,
        v_payload->'content_items'
    );

    -- The marker audit trigger records the moderator as last editor when the
    -- reviewed version differs from the submitted one. Re-stamp approval after
    -- that update so the admin audit remains complete.
    update private.marker_editor_audit
       set approved_by = v_admin,
           approved_at = now()
     where marker_id = v_marker_id;

    return v_marker_id;
end;
$$;

revoke all on function public.review_marker_submission_v2(bigint, text, text, jsonb)
from public, anon, authenticated;

grant execute on function public.review_marker_submission_v2(bigint, text, text, jsonb)
to authenticated;

commit;
