-- DeepMap Editor 2.0 — zone/map titles
-- Public can read published labels; only DeepMap admins can create/edit/delete.

create table if not exists public.map_labels (
    id bigint generated by default as identity primary key,

    game_id text not null,
    map_layer text not null default 'surface',

    slug text not null,
    text_en text not null,
    text_pt text not null,

    coordinate_x double precision not null,
    coordinate_y double precision not null,

    font_size integer not null default 34
        check (font_size between 10 and 160),

    font_weight integer not null default 700
        check (font_weight between 100 and 900),

    color text not null default '#E8D7A4'
        check (color ~ '^#[0-9A-Fa-f]{6}$'),

    opacity double precision not null default 0.82
        check (opacity >= 0 and opacity <= 1),

    uppercase boolean not null default true,
    is_published boolean not null default false,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint map_labels_slug_format
        check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),

    constraint map_labels_game_slug_unique
        unique (game_id, slug),

    constraint map_labels_layer_fk
        foreign key (game_id, map_layer)
        references public.map_layers (game_id, id)
        on update cascade
);

create index if not exists map_labels_map_lookup_idx
    on public.map_labels (game_id, map_layer, is_published, id);

-- updated_at automático

drop trigger if exists deepmap_map_labels_touch_updated_at
on public.map_labels;

create trigger deepmap_map_labels_touch_updated_at
before update on public.map_labels
for each row
execute function private.deepmap_touch_updated_at();

-- RLS / permissões

alter table public.map_labels enable row level security;

revoke all on table public.map_labels
from public, anon, authenticated;

grant select on table public.map_labels
to anon, authenticated;

grant insert, update, delete on table public.map_labels
to authenticated;

grant usage, select on sequence public.map_labels_id_seq
to authenticated;

drop policy if exists "map_labels_public_read"
on public.map_labels;

create policy "map_labels_public_read"
on public.map_labels
for select
to anon, authenticated
using (is_published = true);

drop policy if exists "map_labels_admin_all"
on public.map_labels;

create policy "map_labels_admin_all"
on public.map_labels
for all
to authenticated
using (private.is_deepmap_admin())
with check (private.is_deepmap_admin());
